export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_BLOG = 'FETCH_BLOG';
export const FETCH_BLOGS = 'FETCH_BLOGS';
export const BLOGS_ERROR = 'BLOGS_ERROR';
export const CREATE_BLOG = 'CREATE_BLOG';


export const GET_ACCOUNT_INFO = "GET_ACCOUNT_INFO";
export const GET_ACCOUNT_INFO_ERROR = "GET_ACCOUNT_INFO_ERROR";
